Ha llegado el momento de poner a prueba los conocimientos adquiridos durante la lección. Continuando con el proyecto de las naranjas/toronjas, ahora debes seleccionar parte de los datos. Las columnas que evaluaremos son el diámetro y el peso. Crea arrays específicos para almacenar el diámetro y el peso de la naranja y la toronja. El diámetro está en la columna cero y el peso en la columna uno. Los datos de las naranjas van hasta la fila 4999 y los datos de las toronjas comienzan en la fila 5000 del archivo.

Después de seleccionar los datos, importa la biblioteca matplotlib y crea un gráfico para el peso en función del diámetro tanto para las naranjas como para las toronjas.

In [1]:
import numpy as np

In [2]:
url = 'citrus.csv'

In [7]:
datos = np.loadtxt(url, delimiter=',', dtype=float, skiprows=1, usecols=range(1,6))
datos

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]], shape=(10000, 5))

In [10]:
diametro = datos[:,0]
diametro

array([ 2.96,  3.91,  4.42, ..., 15.59, 15.92, 16.45], shape=(10000,))

In [12]:
diametro_naranjas = diametro[:5000]
diametro_naranjas

array([ 2.96,  3.91,  4.42, ..., 12.55, 12.75, 12.87], shape=(5000,))

In [13]:
diametro_toronjas = diametro[5000:]
diametro_toronjas

array([ 7.63,  7.69,  7.72, ..., 15.59, 15.92, 16.45], shape=(5000,))

In [14]:
peso = datos[:,1]
peso

array([ 86.76,  88.05,  95.17, ..., 256.5 , 260.14, 261.51],
      shape=(10000,))

In [16]:
peso_naranjas = peso[:5000]
peso_naranjas

array([ 86.76,  88.05,  95.17, ..., 218.07, 230.13, 231.09], shape=(5000,))

In [25]:
peso_toronjas = peso[5000:]
peso_toronjas

array([126.79, 133.98, 135.56, ..., 256.5 , 260.14, 261.51], shape=(5000,))

In [1]:
import matplotlib.pyplot as plt

plt.plot(diametro_naranjas, peso_naranjas)
plt.plot(diametro_toronjas, peso_toronjas)

plt.legend(['naranjas', 'toronjas'])

NameError: name 'diametro_naranjas' is not defined